### ISSUE TITLE
东西不错, runloop那段没看懂.

### ISSUE THREAD

**Issue by ytx0574** [858665536/forkingDog#1]
(kCFAllocatorDefault, kCFRunLoopBeforeWaiting, true, 0, ^(CFRunLoopObserverRef observer, CFRunLoopActivity _) {
        // Remove observer when all precache tasks are done.
        if (mutableIndexPathsToBePrecached.count == 0) {
            CFRunLoopRemoveObserver(runLoop, observer, runLoopMode);
            CFRelease(observer);
            return;
        }
        // Pop first index path record as this RunLoop iteration's task.
        NSIndexPath *indexPath = mutableIndexPathsToBePrecached.firstObject;
        [mutableIndexPathsToBePrecached removeObject:indexPath];

```
    // This method creates a "source 0" task in "idle" mode of RunLoop, and will be
    // performed in a future RunLoop iteration only when user is not scrolling.
    [self performSelector:@selector(fd_precacheIndexPathIfNeeded:)
                 onThread:[NSThread mainThread]
               withObject:indexPath
            waitUntilDone:NO
                    modes:@[NSDefaultRunLoopMode]];
});
```

这是个啥, 没看懂 -  -

**Comment by Johnnie-198312** [comment]
http://blog.sunnyxx.com/2015/05/17/cell-height-calculation/ 
(http://blog.sunnyxx.com/2015/05/17/cell-height-calculation/)  看这里
